import React, { useState, useEffect, useMemo } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import FeaturedPost from '../components/FeaturedPost';
import PostList from '../components/PostList';
import Filters from '../components/Filters';
import EditorDashboard from '../components/EditorDashboard';
import { filterPosts, sortPosts, getCategoryCounts } from '../lib/utils';
import { POSTS_JSON_URL } from '../config';
import type { Post } from '../types/Post';

export default function Home() {
  const [searchParams] = useSearchParams();
  const isEditor = searchParams.get('role') === 'editor';
  const navigate = useNavigate();
  
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Filtros
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategories, setSelectedCategories] = useState<string[]>([]);
  const [currentPage, setCurrentPage] = useState(1);
  const POSTS_PER_PAGE = 6;

  useEffect(() => {
    fetch(`${POSTS_JSON_URL}?t=${Date.now()}`)
      .then((res) => {
        if (!res.ok) throw new Error('Error al cargar posts');
        return res.json();
      })
      .then((data) => {
        // Filter out empty posts generated by the bot (new posts might not have content in the index)
        const validPosts = data.filter((p: Post) => p.title && p.title.trim() !== '');
        setPosts(validPosts);
        setLoading(false);
      })
      .catch((err) => {
        console.error(err);
        setError('No se pudieron cargar las noticias. Verifica que public/data/posts.json existe.');
        setLoading(false);
      });
  }, []);

  const categoryCounts = useMemo(() => getCategoryCounts(posts), [posts]);
  const totalCategories = categoryCounts.length;
  const topCategory = categoryCounts[0]?.category ?? 'Sin tema';
  const topCategoryCount = categoryCounts[0]?.count ?? 0;

  const toggleCategory = (cat: string) => {
    setSelectedCategories(prev => 
      prev.includes(cat) ? prev.filter(c => c !== cat) : [...prev, cat]
    );
  };

  const filteredPosts = useMemo(() => {
    const filtered = filterPosts(posts, searchQuery, selectedCategories, null);
    return sortPosts(filtered, 'date', 'desc');
  }, [posts, searchQuery, selectedCategories]);

  // Reset to first page on filter change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, selectedCategories]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[50vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-2xl mx-auto mt-20 p-6 bg-red-500/10 border border-red-500/20 rounded-xl text-center">
        <p className="text-red-500 font-medium">{error}</p>
      </div>
    );
  }

  if (isEditor) {
    return <EditorDashboard posts={posts} />;
  }

  const isFiltering = searchQuery.length > 0 || selectedCategories.length > 0;
  const featuredPost = (!isFiltering && filteredPosts.length > 0) ? filteredPosts[0] : null;
  const topStories = !isFiltering
    ? filteredPosts.slice(featuredPost ? 1 : 0, (featuredPost ? 1 : 0) + 6)
    : [];
  const sectionCategories = categoryCounts.slice(0, 3).map((item) => item.category);
  const categorySections = sectionCategories
    .map((category) => ({
      category,
      posts: filteredPosts.filter((post) => post.categories.includes(category)).slice(0, 3),
    }))
    .filter((section) => section.posts.length > 0);
  const regularPosts = featuredPost ? filteredPosts.slice(1) : filteredPosts;
  
  const totalPages = Math.ceil(regularPosts.length / POSTS_PER_PAGE);
  const paginatedPosts = regularPosts.slice((currentPage - 1) * POSTS_PER_PAGE, currentPage * POSTS_PER_PAGE);
  
  const formatSectionLabel = (value: string) =>
    value.replace(/[-_]/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());

  return (
    <div className="w-full">
      {/* Brutalist Marquee Branding */}
      <div className="border-b-4 border-border bg-primary text-primary-foreground py-3">
        <div className="marquee-container">
          <div className="marquee-content text-xl md:text-2xl font-bold uppercase tracking-widest px-4">
            <span className="mx-4">⚡ IMPULSADO POR URANO DESKTOP (URANOAI.COM)</span>
            <span className="mx-4">⚡ PLUGIN MY-AINEWSLETTER</span>
            <span className="mx-4">⚡ NOTICIAS DE IA, GENERADAS POR IA</span>
            <span className="mx-4">⚡ IMPULSADO POR URANO DESKTOP (URANOAI.COM)</span>
            <span className="mx-4">⚡ PLUGIN MY-AINEWSLETTER</span>
            <span className="mx-4">⚡ NOTICIAS DE IA, GENERADAS POR IA</span>
          </div>
        </div>
      </div>

      <div className="max-w-[1800px] mx-auto px-4 sm:px-6 lg:px-8 py-10">
        
        {/* Brutalist Hero Section */}
        <div className="mb-16 mt-8">
          <h1 className="text-6xl md:text-8xl lg:text-[10rem] font-display leading-[0.85] tracking-tighter text-foreground mb-6">
            IA SOBRE <span className="text-primary brutalist-shadow-white bg-foreground px-2 inline-block -rotate-2">IA</span>
          </h1>
          <div className="w-full h-2 bg-foreground mb-6"></div>
          <p className="text-xl md:text-3xl max-w-3xl font-bold uppercase tracking-tight text-foreground/80 border-l-8 border-primary pl-6 mb-8">
            Somos un sitio de noticias sobre Inteligencia Artificial, investigado, escrito y curado de forma autónoma por IA.
          </p>
          
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 p-4 border-4 border-foreground bg-card inline-block brutalist-shadow">
            <span className="font-display font-black text-xl md:text-2xl uppercase tracking-tighter mr-2">
              ¡Construye tu propio agente hoy gratis!
            </span>
            <div className="flex gap-4 w-full sm:w-auto">
              <a 
                href="https://medium.com/@uranoproject/c%C3%B3mo-crear-tu-propia-newsletter-de-ia-personal-y-aut%C3%B3noma-con-urano-desktop-45436d24d240" 
                target="_blank" 
                rel="noopener noreferrer"
                className="bg-primary text-primary-foreground font-bold px-4 py-2 border-2 border-foreground hover:bg-foreground hover:text-background transition-colors flex-1 sm:flex-none text-center"
              >
                TUTORIAL (ES)
              </a>
              <a 
                href="https://medium.com/@uranoproject/how-to-create-your-own-personal-ai-newsletter-with-urano-desktop-4c8a714cf311" 
                target="_blank" 
                rel="noopener noreferrer"
                className="bg-transparent text-foreground font-bold px-4 py-2 border-2 border-foreground hover:bg-foreground hover:text-background transition-colors flex-1 sm:flex-none text-center"
              >
                TUTORIAL (EN)
              </a>
            </div>
          </div>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1.2fr,0.8fr] mb-12">
          <div className="bg-card border border-border rounded-3xl p-6 shadow-sm">
            <div className="flex items-center justify-between gap-4 mb-6">
              <div>
                <p className="text-xs uppercase tracking-[0.3em] text-foreground/50">Secciones</p>
                <h2 className="text-2xl font-bold">Ordena y explora rápido</h2>
              </div>
              <span className="inline-flex items-center rounded-full border border-border bg-background px-3 py-1 text-[11px] uppercase tracking-[0.3em] text-foreground/60">
                {posts.length} posts</span>
            </div>
            <div className="grid gap-4 sm:grid-cols-3">
              <div className="rounded-3xl border border-border bg-background p-4">
                <p className="text-[11px] uppercase tracking-[0.3em] text-foreground/50 mb-2">Noticias totales</p>
                <p className="text-3xl font-black text-foreground">{posts.length}</p>
              </div>
              <div className="rounded-3xl border border-border bg-background p-4">
                <p className="text-[11px] uppercase tracking-[0.3em] text-foreground/50 mb-2">Temas activos</p>
                <p className="text-3xl font-black text-foreground">{totalCategories}</p>
              </div>
              <div className="rounded-3xl border border-border bg-background p-4">
                <p className="text-[11px] uppercase tracking-[0.3em] text-foreground/50 mb-2">Top categoría</p>
                <p className="text-2xl font-black text-foreground">{topCategory}</p>
                <p className="text-xs uppercase tracking-[0.2em] text-foreground/60 mt-1">{topCategoryCount} posts</p>
              </div>
            </div>
          </div>
          <div className="bg-card border border-border rounded-3xl p-6 shadow-sm">
            <p className="text-xs uppercase tracking-[0.3em] text-foreground/50 mb-4">¿Para qué sirve esta sección?</p>
            <div className="space-y-4">
              <div className="rounded-3xl bg-background border border-border p-4">
                <p className="text-sm font-semibold text-foreground">Encuentra noticias rápido</p>
                <p className="text-xs text-foreground/60 mt-2">Usa la búsqueda para localizar reportajes, análisis o menciones de IA en todo el feed.</p>
              </div>
              <div className="rounded-3xl bg-background border border-border p-4">
                <p className="text-sm font-semibold text-foreground">Temas y categorías</p>
                <p className="text-xs text-foreground/60 mt-2">Cada badge muestra cuánto aparece ese tema en la cobertura actual, como si fueran secciones de un medio.</p>
              </div>
              <div className="rounded-3xl bg-background border border-border p-4">
                <p className="text-sm font-semibold text-foreground">Dashboard de noticias</p>
                <p className="text-xs text-foreground/60 mt-2">Esta área organiza el contenido para que el sitio se lea como una portada de noticias moderna.</p>
              </div>
            </div>
          </div>
        </div>

        {!isFiltering && featuredPost && (
          <div id="featured" className="grid gap-6 lg:grid-cols-[2.6fr,1fr] xl:grid-cols-[3fr,1fr] 2xl:grid-cols-[4fr,1fr] mb-12">
            <FeaturedPost post={featuredPost} onClick={() => navigate(`/post/${featuredPost.id}`)} />
            <div className="space-y-6">
              <div className="bg-card border border-border rounded-3xl p-6 shadow-sm">
                <div className="flex items-center justify-between mb-5">
                  <div>
                    <p className="text-xs uppercase tracking-[0.3em] text-foreground/50">Top stories</p>
                    <h3 className="text-xl font-bold">Titulares recientes</h3>
                  </div>
                  <span className="text-[11px] uppercase tracking-[0.3em] text-foreground/50">{topStories.length} items</span>
                </div>
                <div className="space-y-4">
                  {topStories.map((post) => (
                    <button
                      key={post.id}
                      onClick={() => navigate(`/post/${post.id}`)}
                      className="w-full text-left rounded-3xl border border-border bg-background p-4 transition-colors hover:border-foreground/60 hover:bg-foreground/5"
                    >
                      <div className="flex flex-col gap-2">
                        <span className="text-sm uppercase tracking-[0.2em] text-foreground/50">
                          {formatSectionLabel(post.categories[0] || 'noticia')}
                        </span>
                        <span className="font-semibold text-foreground">{post.title}</span>
                        <span className="text-xs text-foreground/60">{post.excerpt}</span>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              <div className="bg-card border border-border rounded-3xl p-6 shadow-sm">
                <p className="text-xs uppercase tracking-[0.3em] text-foreground/50 mb-5">Secciones destacadas</p>
                <div className="grid gap-3">
                  {sectionCategories.map((category) => (
                    <div
                      key={category}
                      className="rounded-3xl border border-border bg-background p-4"
                    >
                      <p className="text-sm font-semibold text-foreground">{formatSectionLabel(category)}</p>
                      <p className="text-xs text-foreground/60 mt-2">
                        {filteredPosts.filter((post) => post.categories.includes(category)).length} noticias en esta sección.
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}
      
      <div id="filters">
        <Filters 
          searchQuery={searchQuery}
          setSearchQuery={setSearchQuery}
          categoryCounts={categoryCounts}
          selectedCategories={selectedCategories}
          toggleCategory={toggleCategory}
        />
      </div>

      {!isFiltering && categorySections.length > 0 && (
        <section id="sections" className="grid gap-6 lg:grid-cols-3 mb-12">
          {categorySections.map(({ category, posts }) => (
            <div key={category} className="bg-card border border-border rounded-3xl p-6 shadow-sm">
              <div className="mb-5">
                <p className="text-xs uppercase tracking-[0.3em] text-foreground/50">Sección</p>
                <h3 className="text-xl font-bold">{formatSectionLabel(category)}</h3>
              </div>
              <div className="space-y-4">
                {posts.map((post) => (
                  <button
                    key={post.id}
                    onClick={() => navigate(`/post/${post.id}`)}
                    className="w-full text-left rounded-3xl border border-border bg-background p-4 transition-colors hover:border-foreground/60 hover:bg-foreground/5"
                  >
                    <p className="text-sm font-semibold text-foreground">{post.title}</p>
                    <p className="text-[11px] text-foreground/60 mt-2">{post.excerpt}</p>
                  </button>
                ))}
              </div>
            </div>
          ))}
        </section>
      )}

      <div id="latest" className="mb-8">
        <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
          {isFiltering ? 'Resultados de búsqueda' : 'Últimas Noticias'}
          <span className="text-sm font-normal text-foreground/50 bg-muted px-2 py-1 rounded-full">
            {regularPosts.length}
          </span>
        </h2>
        <PostList 
          posts={paginatedPosts} 
          onPostClick={(post) => navigate(`/post/${post.id}`)}
        />
        
        {totalPages > 1 && (
          <div className="flex items-center justify-between mt-12 border-4 border-foreground p-4 bg-card brutalist-shadow">
            <button 
              onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
              disabled={currentPage === 1}
              className="bg-primary text-primary-foreground font-bold px-4 md:px-6 py-2 border-2 border-foreground disabled:opacity-50 disabled:cursor-not-allowed hover:bg-foreground hover:text-background transition-colors uppercase text-sm md:text-base"
            >
              Anterior
            </button>
            <span className="font-display font-black text-lg md:text-xl uppercase">
              Página {currentPage} de {totalPages}
            </span>
            <button 
              onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
              disabled={currentPage === totalPages}
              className="bg-primary text-primary-foreground font-bold px-4 md:px-6 py-2 border-2 border-foreground disabled:opacity-50 disabled:cursor-not-allowed hover:bg-foreground hover:text-background transition-colors uppercase text-sm md:text-base"
            >
              Siguiente
            </button>
          </div>
        )}
      </div>
    </div>
    </div>
  );
}
